@host = localhost
@port = 4000
@hostname = {{host}}:{{port}}
@baseUrl = http://{{hostname}}


### Get start server
GET {{baseUrl}}/
###

### Get An User
GET {{baseUrl}}/user/info/74241739

### Get An Company
GET {{baseUrl}}/company/info/20614963540