// table schema generated by introspection
import { pgTable, integer, unique, text, smallint, date } from "drizzle-orm/pg-core"

const users = pgTable("users", {
    id: integer().primaryKey().generatedAlwaysAsIdentity(),
    document: integer().notNull(),
    father_lastname: text(),
    mother_lastname: text(),
    names: text(),
    birth_date: date(),
    registration_date: date(),
    issue_date: date(),
    expiration_date: date(),
    birth_ubigeo: text(),
    address_ubigeo: text(),
    address: text(),
    gender: smallint(),
    civil_status: text(),
    digit_ruc: smallint(),
    mother: text(),
    father: text(),
}, (table) => [
    unique("idx_users_document").on(table.document),
]);

export { users }